version: "3.9"
services:
  postgres:
    image: "postgres"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
     POSTGRES_USER: "student"
     POSTGRES_PASSWORD: "666777"
     POSTGRES_DB: "kupipodariday"

  backend:
     container_name: "backend-kupipodariday"
     build: "./backend"
     ports: 
     - "4000:3000"
     depends_on: 
     - postgres

  frontend:
    container_name: "frontend-kupipodariday"
    build: "./frontend"
    
    ports: 
    - "3010:80"
    tty: true
    stdin_open: true
    depends_on: 
     - backend

