version: "3.9"
services:
  postgres:
    image: "postgres"
    container_name: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - data:/var/lib/postgresql/data
  backend:
     container_name: "backend-kupipodariday"
     build: "./backend"
     ports: 
     - "4000:3000"
     depends_on: 
     - postgres
  frontend:
    container_name: "frontend-kupipodariday"
    build: "./frontend"
    
    ports: 
    - "3010:80"
    tty: true
    stdin_open: true
    depends_on: 
     - backend
volumes:
 data:
