version: "3.9"
services:
  postgres:
    image: "postgres"
    container_name: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - data:/var/lib/postgresql/data
  backend:
     container_name: "backend-kupipodariday"
     image: "lexv/web-plus-docker-and-compose-backend"
     env_file:
      - ./.env
     ports: 
     - "4000:3000"
     depends_on: 
     - postgres
  frontend:
    container_name: "frontend-kupipodariday"
    image: "lexv/web-plus-docker-and-compose-frontend"
    ports: 
    - "3010:80"
    tty: true
    stdin_open: true
    depends_on: 
     - backend
volumes:
 data:
